export type RootStackParamList = {
  First: undefined;
    NoReport: undefined;
    ReportMain: undefined;
    EconomyStudy: undefined;
    EconomyWordScreen: undefined;
    EconomyWordDetailScreen: { word: string };
    EconomyNewsDetailScreen: {id:number};
    Report: undefined;
    DetailReport: { selectedYear: number; selectedMonth: number;report:any };
    StockMain: undefined;
    Stock: undefined;
    Login: undefined;
    Main: undefined;
    Home: undefined;
    Profile: undefined;
    FindPassword: undefined;
    ChangePassword: undefined;
    FindId: undefined;
  };